#!/bin/sh
#

###########################
## chapter definitions
###########################

#
# cursus in NL voor cvo-tsm hieronder
# Datacommunicatie en netwerken
#

#
chapt_20090909() {
	MODULES=""
	chaptitle="inleiding"
	add_mod mod_cvotsm/20090909.xml
	}

#
chapt_20090916() {
	MODULES=""
	chaptitle="basisterminologie netwerken"
	add_mod mod_cvotsm/20090916.xml
	}

#
chapt_20090923() {
	MODULES=""
	chaptitle="reis door lagen"
	add_mod mod_cvotsm/20090923.xml
	}

#
chapt_20090930() {
	MODULES=""
	chaptitle="ip adressen"
	add_mod mod_cvotsm/20090930.xml
	}

#
chapt_tellen() {
	MODULES=""
	chaptitle="tellen"
	add_mod mod_cvotsm/tellen.xml
	}

#
chapt_20091007() {
	MODULES=""
	chaptitle="binaire subnets"
	add_mod mod_cvotsm/20091007.xml
	}

#
chapt_testokt() {
	MODULES=""
	chaptitle="test oktober"
	add_mod mod_cvotsm/testokt.xml
	}

#
chapt_testoktopl() {
	MODULES=""
	chaptitle="test oktober oplossing"
	add_mod mod_cvotsm/testoktopl.xml
	}

#
chapt_20091014() {
	MODULES=""
	chaptitle="supernetten"
	add_mod mod_cvotsm/20091014.xml
	}

#
chapt_20091015() {
	MODULES=""
	chaptitle="huiswerk"
	add_mod mod_cvotsm/20091015.xml
	}

#
chapt_20091015b() {
	MODULES=""
	chaptitle="huiswerk oplossing"
	add_mod mod_cvotsm/20091015b.xml
	}

#
chapt_20091021() {
	MODULES=""
	chaptitle="DNS"
	add_mod mod_cvotsm/20091021.xml
	}

#
chapt_20091028() {
	MODULES=""
	chaptitle="modems"
	add_mod mod_cvotsm/20091028.xml
	}

#
chapt_20091117() {
	MODULES=""
	chaptitle="wireless"
	add_mod mod_cvotsm/20091117.xml
	}

#
chapt_20091119() {
	MODULES=""
	chaptitle="demo DNS"
	add_mod mod_cvotsm/20091119.xml
	}

#
chapt_20091130() {
	MODULES=""
	chaptitle="zelf netwerk bouwen"
	add_mod mod_cvotsm/20091130.xml
	}

#
chapt_20091207() {
	MODULES=""
	chaptitle="demo DHCP"
	add_mod mod_cvotsm/20091207.xml
	}

#
chapt_20091216() {
	MODULES=""
	chaptitle="demo router en webserver"
	add_mod mod_cvotsm/20091216.xml
	}

#
chapt_20091217() {
	MODULES=""
	chaptitle="extra tekeningen"
	add_mod mod_cvotsm/20091217.xml
	}

#
# cursus in NL voor cvo-tsm hieronder
# 2010 Datacommunicatie en netwerken
#

#
chapt_20100904() {
	MODULES=""
	chaptitle="inleiding"
	add_mod mod_cvotsm/20100904.xml
	}

#
chapt_gnufdl() {
	MODULES=""
	chaptitle="GNU FDL"
	add_mod mod_license/gnufdl.xml
	}

