#!/bin/sh
#

BOOKTITLE="Datacommunicatie en netwerken"
TEACHER="Paul Cobbaut"

###########################
## chapter definitions
###########################

. $BOOKSDIR/chapters
	
##################
# define book
##################

# define book as chapters in certain order

# cvo datacommunicatie en netwerken
add_chapt 20100904
add_appen gnufdl
